import { Metadata } from 'next';

export const metadata: Metadata = {
	title: '13gucci | Contact',
	description: 'Generated by create next app',
};

export default function ContactPage() {
	return <div>Contact Page</div>;
}
